spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 300 # amount of simultaneous connections
      minimum-idle: 10 # amount of ready connections
      connection-timeout: 10000 # waiting time before error
      pool-name: AuthHikariPool # Name for monitoring
  threads:
    virtual:
      enabled: true

  jpa:
    # database: postgresql
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate # validate tables structure
    properties:
      hibernate:
        # optimization: group multiple INSERT/UPDATE statements into single network packets.
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
        # disable formatting to save CPU cycles
        format_sql: false